In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor # import the random forest model
from sklearn import  preprocessing # used for label encoding and imputing NaNs
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score

import datetime as dt # we will need this to convert the date to a number of days since some point

from sklearn.tree import export_graphviz
from sklearn import tree

# Acceptance Status will be predicted using 3 models

In [2]:
claimsdata = pd.read_csv("C:/Users/Laval/Downloads/MSCatUOM/data-science/project/data/Natera-processed-cleaned-data.csv")
claimsdata.head()

,Ticket Number,Date of Service,Carrier Code,Charges,Payments,Insurance Payment,Patient Payment,Writeoffs,FinancialClass,CPT,...,Payment Post Date,NPI,Ordering Clinic,Denied Code,First Billed Date,Provider Profile,Insurance Bal,Patient Bal,Allowed Amount,Case Count
0,104452,1/2/2019,CFHP-E2,"$3,900.00",$0.00,$0.00,$0.00,$0.00,NC - NON-CONTRACTED,81507,...,1/22/2019,1316428238,ALAMO WOMEN'S OBGYN,197,1/8/2019,NTINC,$0.00,"$3,900.00",$0.00,1
1,104453,1/2/2019,CFHP-E2,"$3,900.00",$0.00,$0.00,$0.00,$0.00,NC - NON-CONTRACTED,81507,...,1/24/2019,1316428238,ALAMO WOMEN'S OBGYN,197,1/8/2019,NTINC,$0.00,"$3,900.00",$0.00,1
2,104454,1/2/2019,NCS,$795.00,$249.00,$0.00,$249.00,$546.00,SP - SELF PAY,99999,...,2/10/2019,1699760116,COMPREHENSIVE WOMEN'S HEALTHCARE,-,-,NTINC,$0.00,$0.00,$0.00,1
3,104496,1/2/2019,AETLIF-E,"$3,900.00",$0.00,$0.00,$0.00,$0.00,CT - CONTRACTED,81420,...,1/28/2019,1609216597,PEACHTREE WOMEN'S CLINIC - NORTHSIDE,-,1/8/2019,NTINC,"$3,900.00",$0.00,$749.00,1
4,104497,1/2/2019,AETLIF-E,"$3,900.00",$0.00,$0.00,$0.00,$0.00,CT - CONTRACTED,81420,...,1/30/2019,1609216597,PEACHTREE WOMEN'S CLINIC - NORTHSIDE,-,1/8/2019,NTINC,"$3,900.00",$0.00,$749.00,1

In [80]:
#import the data as dates for date of service and 
claimsdata = pd.read_csv("processedData.csv", parse_dates=['DateOfService', 'FirstBilledDate'])
claimsdata.head()

,Ticket Number,DateOfService,CarrierCode,Charges,Payments,InsurancePayment,PatientPayment,Writeoffs,InsuranceBal,PatientBal,...,CPT,DateOfEntry,PaymentPostDate,NPI,OrderingClinic,DeniedCode,FirstBilledDate,ProviderProfile,CaseCount,accepted
0,104452,2019-01-02,CFHP-E2,3900,0.0,0.0,0.0,0.0,0.0,3900.0,...,81507,1/7/2019,1/22/2019,1316428238,ALAMO WOMEN'S OBGYN,197,2019-01-08,NTINC,1,False
1,104453,2019-01-02,CFHP-E2,3900,0.0,0.0,0.0,0.0,0.0,3900.0,...,81507,1/7/2019,1/24/2019,1316428238,ALAMO WOMEN'S OBGYN,197,2019-01-08,NTINC,1,False
2,104454,2019-01-02,NCS,795,249.0,0.0,249.0,546.0,0.0,0.0,...,99999,1/7/2019,2/10/2019,1699760116,COMPREHENSIVE WOMEN'S HEALTHCARE,-,NaT,NTINC,1,True
3,104496,2019-01-02,AETLIF-E,3900,0.0,0.0,0.0,0.0,3900.0,0.0,...,81420,1/7/2019,1/28/2019,1609216597,PEACHTREE WOMEN'S CLINIC - NORTHSIDE,-,2019-01-08,NTINC,1,True
4,104497,2019-01-02,AETLIF-E,3900,0.0,0.0,0.0,0.0,3900.0,0.0,...,81420,1/7/2019,1/30/2019,1609216597,PEACHTREE WOMEN'S CLINIC - NORTHSIDE,-,2019-01-08,NTINC,1,True

In [81]:
# Convert the date into a number (date gaps between DOS and FirstBilledDate)
claimsdata[claimsdata.FirstBilledDate.isnull()]

,Ticket Number,DateOfService,CarrierCode,Charges,Payments,InsurancePayment,PatientPayment,Writeoffs,InsuranceBal,PatientBal,...,CPT,DateOfEntry,PaymentPostDate,NPI,OrderingClinic,DeniedCode,FirstBilledDate,ProviderProfile,CaseCount,accepted
2,104454,2019-01-02,NCS,795,249.0,0.0,249.0,546.0,0.0,0.0,...,99999,1/7/2019,2/10/2019,1699760116,COMPREHENSIVE WOMEN'S HEALTHCARE,-,NaT,NTINC,1,True
50,116442,2019-01-02,SELF,1590,249.0,0.0,249.0,1341.0,0.0,0.0,...,99999,1/9/2019,1/22/2019,1497129134,ELITE WOMEN'S HEALTH,-,NaT,NTINC,1,True
146,120265,2019-01-02,NCS,795,249.0,0.0,249.0,546.0,0.0,0.0,...,99999,1/10/2019,1/31/2019,1699015362,OBSTETRICAL AND GYNECOLOGICAL ASSOCIATES,-,NaT,NTINC,1,True
194,123255,2019-01-02,SELF,1590,249.0,0.0,249.0,0.0,0.0,1341.0,...,99999,1/10/2019,2/13/2019,1831691401,MERCY BIRTHING CENTER - ST. LOUIS,-,NaT,NTINC,1,True
223,123576,2019-01-02,SELF,795,249.0,0.0,249.0,546.0,0.0,0.0,...,99999,1/10/2019,2/5/2019,1821555392,"ARBOR DIAGNOSTICS, INC (CLIENT BILL)",-,NaT,NTINC,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19933,292748,2019-01-02,SELF,1590,249.0,0.0,249.0,1341.0,0.0,0.0,...,99999,1/29/2019,2/13/2019,1114025749,FARIS A HANNA OBGYN,-,NaT,NTINC,1,True
20299,294099,2019-01-03,SELF,649,349.0,0.0,349.0,300.0,0.0,0.0,...,99999,1/29/2019,2/13/2019,1194991463,CAROLINAS FERTILITY INSTITUTE,-,NaT,NTINC,1,True
20644,294858,2019-01-07,NCS,795,249.0,0.0,249.0,546.0,0.0,0.0,...,99999,1/29/2019,2/10/2019,1750383048,NEW JERSEY PERINATAL- WESTFIELD,-,NaT,NTINC,1,True
21204,300561,2019-01-02,SELF,649,349.0,0.0,349.0,300.0,0.0,0.0,...,99999,1/30/2019,2/13/2019,1720068562,MAYO CLINIC,-,NaT,NTINC,1,True
21446,301161,2019-01-06,SELF,649,99.0,0.0,99.0,550.0,0.0,0.0,...,99999,1/30/2019,1/31/2019,1720068562,MAYO CLINIC,-,NaT,NTINC,1,True

As we have enough data, small number of data is NAT, we can drop those rows)

In [82]:
claimsdata = claimsdata.dropna(subset=['FirstBilledDate'])
claimsdata['timedelta'] = (claimsdata['FirstBilledDate'] - claimsdata['DateOfService']).dt.days.astype(int)
claimsdata[['DateOfService', 'FirstBilledDate', 'timedelta']].head()

  DateOfService FirstBilledDate  timedelta
0    2019-01-02      2019-01-08          6
1    2019-01-02      2019-01-08          6
3    2019-01-02      2019-01-08          6
4    2019-01-02      2019-01-08          6
5    2019-01-02      2019-01-08          6

In [83]:
#Encoding categorical features
#naive approach and assign a numeric value to each categorical feature
#LabelEncoder()

In [84]:
claimsdata['NPI'] = claimsdata['NPI'].astype('object')
for c in claimsdata.columns:
    if claimsdata[c].dtype == 'object':
        lbl = preprocessing.LabelEncoder()
        lbl.fit(list(claimsdata[c].values)) 
        claimsdata[c] = lbl.transform(list(claimsdata[c].values))

In [85]:
#categorical data preprocess done
claimsdata.head()

,Ticket Number,DateOfService,CarrierCode,Charges,Payments,InsurancePayment,PatientPayment,Writeoffs,InsuranceBal,PatientBal,...,DateOfEntry,PaymentPostDate,NPI,OrderingClinic,DeniedCode,FirstBilledDate,ProviderProfile,CaseCount,accepted,timedelta
0,104452,2019-01-02,119,3900,0.0,0.0,0.0,0.0,0.0,3900.0,...,16,8,894,44,27,2019-01-08,0,1,False,6
1,104453,2019-01-02,119,3900,0.0,0.0,0.0,0.0,0.0,3900.0,...,16,10,894,44,27,2019-01-08,0,1,False,6
3,104496,2019-01-02,14,3900,0.0,0.0,0.0,0.0,3900.0,0.0,...,16,13,1722,1077,0,2019-01-08,0,1,True,6
4,104497,2019-01-02,14,3900,0.0,0.0,0.0,0.0,3900.0,0.0,...,16,15,1722,1077,0,2019-01-08,0,1,True,6
5,104498,2019-01-02,14,4100,0.0,0.0,0.0,0.0,0.0,4100.0,...,16,13,1722,1077,69,2019-01-08,0,1,False,6

In [86]:
# Convert NPI as object attribute
X_claims = claimsdata.drop(['Ticket Number', 'CaseCount', 'DateOfService', 'FirstBilledDate', 'DeniedCode', 'PaymentPostDate', 'DateOfEntry', 'accepted'], axis=1)
y_claims = claimsdata['accepted']

In [87]:
X_claims.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22562 entries, 0 to 22695
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CarrierCode       22562 non-null  int64
 1   Charges           22562 non-null  int64
 2   Payments          22562 non-null  float64
 3   InsurancePayment  22562 non-null  float64
 4   PatientPayment    22562 non-null  float64
 5   Writeoffs         22562 non-null  float64
 6   InsuranceBal      22562 non-null  float64
 7   PatientBal        22562 non-null  float64
 8   AllowedAmount     22562 non-null  float64
 9   FinancialClass    22562 non-null  int64
 10  CPT               22562 non-null  int64
 11  NPI               22562 non-null  int64
 12  OrderingClinic    22562 non-null  int64
 13  ProviderProfile   22562 non-null  int64
 14  timedelta         22562 non-null  int32
dtypes: float64(7), int32(1), int64(7)
memory usage: 2.7 MB

In [88]:
X_claims.shape

(22562, 15)

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X_claims, y_claims, test_size = 0.20)

In [90]:
X_train.shape

(18049, 15)

In [91]:
X_test.shape

(4513, 15)

In [92]:
#decision tree

In [93]:
model = tree.DecisionTreeClassifier()

In [94]:
model.fit(X = X_train, y = y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [95]:
y_pred = model.predict(X_test)
# Check the training error
model.score(X_test, y_test)

0.9663195213826723

Feature Selection By Gradient Boost Tree for RandomForestClassifier

In [96]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

In [97]:
def run_randomForest(X_train, X_test, y_train, y_test):
    clf = RandomForestClassifier(n_estimators=100, random_state=0, n_jobs=-1)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print("Accuracy: ", accuracy_score(y_test,y_pred))

In [98]:
def run_gradientBoostingForest(X_train, X_test, y_train, y_test):
    clf = GradientBoostingClassifier(n_estimators=100, random_state=0)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print("Accuracy: ", accuracy_score(y_test,y_pred))

In [ ]:
for index in range(1, 16):
    gradientBoostRFELoop = RFE(GradientBoostingClassifier(n_estimators=100, random_state=0),n_features_to_select = index)
    gradientBoostRFELoop.fit(X_train,y_train)
    X_train_Grad_RFELoop = gradientBoostRFELoop.transform(X_train)
    X_test_Grad_RFELoop = gradientBoostRFELoop.transform(X_test)
    print("number of selected features:", index)
    run_randomForest(X_train_Grad_RFELoop, X_test_Grad_RFELoop, y_train, y_test)
    print()

number of selected features: 1
Accuracy:  0.7952581431420341

number of selected features: 2
Accuracy:  0.8595169510303567

number of selected features: 3
Accuracy:  0.9164635497451806

number of selected features: 4
Accuracy:  0.9213383558608464

Gradient Boosting Algorithm for RFE

In [77]:
for index in range(1, 16):
    gradientBoostRFELoop = RFE(GradientBoostingClassifier(n_estimators=100, random_state=0),n_features_to_select = index)
    gradientBoostRFELoop.fit(X_train,y_train)
    X_train_Grad_RFELoop = gradientBoostRFELoop.transform(X_train)
    X_test_Grad_RFELoop = gradientBoostRFELoop.transform(X_test)
    print("number of selected features:", index)
    run_gradientBoostingForest(X_train_Grad_RFELoop, X_test_Grad_RFELoop, y_train, y_test)
    print()

number of selected features: 1
Accuracy:  0.8010192776423665

number of selected features: 2
Accuracy:  0.8298249501440284

number of selected features: 3
Accuracy:  0.8431198759140262

number of selected features: 4
Accuracy:  0.8648349213383558

number of selected features: 5
Accuracy:  0.8732550409926878

number of selected features: 6
Accuracy:  0.8748061156658542

number of selected features: 7
Accuracy:  0.8785730113006869

number of selected features: 8
Accuracy:  0.8847773099933526

number of selected features: 9
Accuracy:  0.8807888322623532

number of selected features: 10
Accuracy:  0.8847773099933526

number of selected features: 11
Accuracy:  0.888101041435852

number of selected features: 12
Accuracy:  0.8909816086860182

number of selected features: 13
Accuracy:  0.888101041435852

number of selected features: 14
Accuracy:  0.8843341458010193

number of selected features: 15
Accuracy:  0.8856636383780191

Feature Selection By Random Forest for RandomForestClassifier

In [58]:
for index in range(1, 16):
    randomForestRFELoop = RFE(RandomForestClassifier(n_estimators=100, random_state=0, n_jobs=-1),n_features_to_select = index)
    randomForestRFELoop.fit(X_train,y_train)
    X_train_RandForest_RFELoop = randomForestRFELoop.transform(X_train)
    X_test_RandForest_RFELoop = randomForestRFELoop.transform(X_test)
    print("selected features:", index)
    run_randomForest(X_train_RandForest_RFELoop, X_test_RandForest_RFELoop, y_train, y_test)
    print()

selected features: 1
Accuracy:  0.8007976955461998

selected features: 2
Accuracy:  0.8666075781076888

selected features: 3
Accuracy:  0.9011743851096832

selected features: 4
Accuracy:  0.9477066253046754

selected features: 5
Accuracy:  0.9545756702858409

selected features: 6
Accuracy:  0.953910923997341

selected features: 7
Accuracy:  0.9528030135165079

selected features: 8
Accuracy:  0.9605583868823399

selected features: 9
Accuracy:  0.9665411034788389

selected features: 10
Accuracy:  0.9694216707290051

selected features: 11
Accuracy:  0.9654331929980058

selected features: 12
Accuracy:  0.9703079991136716

selected features: 13
Accuracy:  0.964103700421006

selected features: 14
Accuracy:  0.9660979392865057

selected features: 15
Accuracy:  0.9652116109018392

Feature Selection By DecisionTree for DecisionTreeClassifier

In [62]:
def run_decisionTree(X_train, X_test, y_train, y_test):
    model = tree.DecisionTreeClassifier()
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    print("Score: ", model.score(X_test, y_test))

In [72]:
for depth in range(1,10):
    print("****************************","depth: ",depth," ******************************")
    for index in range(1, 16):
        decisionTreeRFELoop = RFE(tree.DecisionTreeClassifier(max_depth = depth),n_features_to_select = index)
        decisionTreeRFELoop.fit(X_train,y_train)
        X_train_DecisionTree_RFELoop = decisionTreeRFELoop.transform(X_train)
        X_test_DecisionTree_RFELoop = decisionTreeRFELoop.transform(X_test)
        print("selected features:", index)
        run_decisionTree(X_train_DecisionTree_RFELoop, X_test_DecisionTree_RFELoop, y_train, y_test)
        print()

**************************** depth:  1  ******************************
selected features: 1
Score:  0.8007976955461998

selected features: 2
Score:  0.8003545313538666

selected features: 3
Score:  0.8003545313538666

selected features: 4
Score:  0.891646354974518

selected features: 5
Score:  0.8985153999556836

selected features: 6
Score:  0.9142477287835143

selected features: 7
Score:  0.9246620873033459

selected features: 8
Score:  0.947928207400842

selected features: 9
Score:  0.9514735209395081

selected features: 10
Score:  0.955683580766674

selected features: 11
Score:  0.9514735209395081

selected features: 12
Score:  0.9547972523820075

selected features: 13
Score:  0.9565699091513405

selected features: 14
Score:  0.9592288943053401

selected features: 15
Score:  0.9680921781520053

**************************** depth:  2  ******************************
selected features: 1
Score:  0.8007976955461998

selected features: 2
Score:  0.8493241746066917

selected features: 3
Score:  0.8652780855306891

selected features: 4
Score:  0.865942831819189

selected features: 5
Score:  0.8666075781076888

selected features: 6
Score:  0.9381785951695103

selected features: 7
Score:  0.9399512519388433

selected features: 8
Score:  0.9528030135165079

selected features: 9
Score:  0.952138267228008

selected features: 10
Score:  0.9559051628628407

selected features: 11
Score:  0.9543540881896743

selected features: 12
Score:  0.9534677598050078

selected features: 13
Score:  0.9583425659206736

selected features: 14
Score:  0.9596720584976733

selected features: 15
Score:  0.9672058497673388

**************************** depth:  3  ******************************
selected features: 1
Score:  0.8007976955461998

selected features: 2
Score:  0.8391313981830268

selected features: 3
Score:  0.8666075781076888

selected features: 4
Score:  0.9224462663416796

selected features: 5
Score:  0.9228894305340128

selected features: 6
Score:  0.9379570130733437

selected features: 7
Score:  0.9386217593618436

selected features: 8
Score:  0.9443828938621759

selected features: 9
Score:  0.9421670729005096

selected features: 10
Score:  0.9578994017283403

selected features: 11
Score:  0.9596720584976733

selected features: 12
Score:  0.9656547750941724

selected features: 13
Score:  0.9647684467095059

selected features: 14
Score:  0.9649900288056725

selected features: 15
Score:  0.9665411034788389

**************************** depth:  4  ******************************
selected features: 1
Score:  0.8007976955461998

selected features: 2
Score:  0.8391313981830268

selected features: 3
Score:  0.8666075781076888

selected features: 4
Score:  0.9224462663416796

selected features: 5
Score:  0.9326390427653446

selected features: 6
Score:  0.9321958785730113

selected features: 7
Score:  0.934190117438511

selected features: 8
Score:  0.9574562375360071

selected features: 9
Score:  0.9594504764015067

selected features: 10
Score:  0.9610015510746732

selected features: 11
Score:  0.9585641480168402

selected features: 12
Score:  0.9601152226900066

selected features: 13
Score:  0.9680921781520053

selected features: 14
Score:  0.9667626855750056

selected features: 15
Score:  0.9674274318635054

**************************** depth:  5  ******************************
selected features: 1
Score:  0.8007976955461998

selected features: 2
Score:  0.8597385331265234

selected features: 3
Score:  0.8876578772435187

selected features: 4
Score:  0.922224684245513

selected features: 5
Score:  0.9333037890538445

selected features: 6
Score:  0.9512519388433415

selected features: 7
Score:  0.9488145357855086

selected features: 8
Score:  0.9481497894970087

selected features: 9
Score:  0.95989364059384

selected features: 10
Score:  0.9590073122091735

selected features: 11
Score:  0.9698648349213383

selected features: 12
Score:  0.9694216707290051

selected features: 13
Score:  0.9665411034788389

selected features: 14
Score:  0.9638821183248394

selected features: 15
Score:  0.965876357190339

**************************** depth:  6  ******************************
selected features: 1
Score:  0.8007976955461998

selected features: 2
Score:  0.8597385331265234

selected features: 3
Score:  0.909594504764015

selected features: 4
Score:  0.9224462663416796

selected features: 5
Score:  0.9335253711500111

selected features: 6
Score:  0.9505871925548416

selected features: 7
Score:  0.9499224462663417

selected features: 8
Score:  0.9563483270551739

selected features: 9
Score:  0.9647684467095059

selected features: 10
Score:  0.9674274318635054

selected features: 11
Score:  0.9709727454021715

selected features: 12
Score:  0.9689785065366718

selected features: 13
Score:  0.9665411034788389

selected features: 14
Score:  0.9669842676711722

selected features: 15
Score:  0.968313760248172

**************************** depth:  7  ******************************
selected features: 1
Score:  0.8007976955461998

selected features: 2
Score:  0.8597385331265234

selected features: 3
Score:  0.9104808331486816

selected features: 4
Score:  0.9224462663416796

selected features: 5
Score:  0.9337469532461777

selected features: 6
Score:  0.9499224462663417

selected features: 7
Score:  0.9596720584976733

selected features: 8
Score:  0.9612231331708398

selected features: 9
Score:  0.964103700421006

selected features: 10
Score:  0.9678705960558387

selected features: 11
Score:  0.9692000886328385

selected features: 12
Score:  0.9676490139596721

selected features: 13
Score:  0.9663195213826723

selected features: 14
Score:  0.9678705960558387

selected features: 15
Score:  0.9676490139596721

**************************** depth:  8  ******************************
selected features: 1
Score:  0.8007976955461998

selected features: 2
Score:  0.8597385331265234

selected features: 3
Score:  0.8949700864170175

selected features: 4
Score:  0.927542654553512

selected features: 5
Score:  0.9344116995346776

selected features: 6
Score:  0.9501440283625083

selected features: 7
Score:  0.9607799689785065

selected features: 8
Score:  0.9563483270551739

selected features: 9
Score:  0.9649900288056725

selected features: 10
Score:  0.9676490139596721

selected features: 11
Score:  0.9652116109018392

selected features: 12
Score:  0.9667626855750056

selected features: 13
Score:  0.9672058497673388

selected features: 14
Score:  0.9660979392865057

selected features: 15
Score:  0.9685353423443386

**************************** depth:  9  ******************************
selected features: 1
Score:  0.8007976955461998

selected features: 2
Score:  0.8597385331265234

selected features: 3
Score:  0.8954132506093507

selected features: 4
Score:  0.9279858187458453

selected features: 5
Score:  0.9337469532461777

selected features: 6
Score:  0.9501440283625083

selected features: 7
Score:  0.9576778196321737

selected features: 8
Score:  0.9605583868823399

selected features: 9
Score:  0.9625526257478396

selected features: 10
Score:  0.9652116109018392

selected features: 11
Score:  0.9656547750941724

selected features: 12
Score:  0.9654331929980058

selected features: 13
Score:  0.9643252825171726

selected features: 14
Score:  0.968313760248172

selected features: 15
Score:  0.9654331929980058

We can clearly see we have higher accuracy with all these classifiers for 11, 12 feature analysis

Random Forest with RFE using Gradient Boosting:
    number of selected features: 12
    Accuracy:  0.9703079991136716
Random Forest with RFE using Random Forest:
    selected features: 12
    Accuracy:  0.9703079991136716
Gradient Boosting with RFE using Gradient Boosting:
    number of selected features: 12
    Accuracy:  0.8909816086860182
Decision Tree with RFE using Decision Tree:
    selected features: 11
    Score:  0.9709727454021715
    max_depth: 6
for decision trees when max_depth increases model is overfitting, best one at max_depth 6